build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.16
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.16

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ChatGPT Connector"
  org.opencontainers.image.description: "ChatGPT Connector pro Home Assistant"
  org.opencontainers.image.source: "https://github.com/jan-stuchlik/chatgpt_connector"
  org.opencontainers.image.licenses: "Apache License 2.0" 